name: ci

on:
  push:

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com
  IMAGE_NAME: gui # ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          # tags: |
          #   type=sha
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: tz039e
          password: ${{ secrets.ALI_CR_PASSWD }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}